apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers
  labels:
    app: customers
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0  
  selector:
    matchLabels:
      app: customers
  template:
    metadata:
      labels:
        app: customers
    spec:
      restartPolicy: Always
      containers:
      - name: customers
        image: cluster-registry:5000/customers:1.0
        # image: customers
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
          - name: DATABASE_URI
            valueFrom:
              secretKeyRef:
                name: redis-creds
                key: database-uri
        resources:
          limits:
            cpu: "0.25"
            memory: "64Mi"
          requests:
            cpu: "0.10"
            memory: "32Mi"
