name: CI Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.11-slim

    # Required services    
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: sup3r-s3cr3t
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    # Steps for the build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
            
      - name: Install dependencies
        run: |
          python -m pip install psycopg2-binary
          python -m pip install poetry
          poetry config virtualenvs.create false
          poetry lock --no-update
          poetry install

      - name: Run make lint
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 service tests --count --select=E9,F63,F7,F82 --show-source --statistics
          # test for complexity. The GitHub editor is 127 chars wide
          flake8 service tests --count --max-complexity=10 --max-line-length=127 --statistics
          # Run pylint to catch other PEP8 errors
          pylint service tests --max-line-length=127
    
      - name: Wait for database connection
        run: |
            for i in {1..30}; do
              pg_isready -h postgres -p 5432 && break
              sleep 1
            done

      - name: Run unit tests with PyTest
        env:
          DATABASE_URI: postgresql+psycopg2://postgres:sup3r-s3cr3t@postgres:5432/testdb
        run: pytest --pspec --cov=service --cov-report=xml --cov-fail-under=95
    
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3.1.4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
